In [1]:
%use lets-plot
%use dataframe

In [35]:
import java.io.File

fun loadJsonFilesToDataFrame(directoryPath: String): List<File> {
  val dir = File(directoryPath)
  require(dir.isDirectory) { "The provided path is not a directory: $directoryPath" }

  val jsonFiles = dir.listFiles { file -> file.extension == "json" }
  require(!jsonFiles.isNullOrEmpty()) { "No JSON files found in the directory: $directoryPath" }

  return jsonFiles.toList()
}

In [36]:
val files = loadJsonFilesToDataFrame("../experiment/archive2").map { it.path }
val allExperiments = files.map { DataFrame.read(it) }.reduce{ it1, it2 -> it1.concat(it2)}

In [37]:
allExperiments.select { name and time }.sortByDesc { time }

name,time
optimistic_napier,1737022973512
laughing_chandrasekhar,1737022153487
nice_colden,1737022079019
vigilant_spence,1737021492898
vigilant_pike,1737019828459
confident_archimedes,1737019202404
festive_bartik,1737018661589
gracious_zhukovsky,1737018552801
funny_chatterjee,1737016643933
priceless_raman,1737015430507
eloquent_kirch,1737015179555
eager_hypatia,1737015017922
bold_hodgkin,1736970251630
youthful_proskuriakova,1736970010850
sweet_bell,1736969798062
beautiful_spence,1736969623957
musing_bassi,1736968422765
busy_lalande,1736962630117

In [38]:
allExperiments.sortByDesc { globalStats.bestFitness.max }
  .select { name and globalStats.bestFitness.max and parameters.gridDimensions and parameters.gridObstacles and parameters.mutationProbability and parameters.crossoverProbability and parameters.maxTreeDepth }

name,max,gridDimensions,gridObstacles,mutationProbability,crossoverProbability,maxTreeDepth
eloquent_kirch,"100,000000",7,12,"0,700000","0,800000",4
funny_chatterjee,"100,000000",9,18,"0,700000","0,800000",4
gracious_zhukovsky,"98,884921",7,12,"0,500000","0,600000",2
nice_colden,"98,773810",7,12,"0,500000","0,600000",2
vigilant_spence,"95,585317",7,12,"0,700000","0,800000",3
laughing_chandrasekhar,"91,916122",9,18,"0,500000","0,600000",2
optimistic_napier,"91,475490",7,12,"0,500000","0,600000",2
youthful_proskuriakova,"83,266667",9,21,"0,700000","0,800000",2
musing_bassi,"67,783333",9,21,"0,700000","0,800000",2
confident_archimedes,"67,324561",9,18,"0,700000","0,800000",3
busy_lalande,"48,752274",9,21,"0,700000","0,800000",2
beautiful_spence,"44,311111",7,12,"0,500000","0,600000",2
bold_hodgkin,"44,156156",7,12,"0,500000","0,600000",2
priceless_raman,"40,000000",9,18,"0,700000","0,800000",4
festive_bartik,"30,416667",9,18,"0,700000","0,800000",4
sweet_bell,"22,400000",9,21,"0,700000","0,800000",2
eager_hypatia,"22,250000",7,12,"0,700000","0,800000",4
vigilant_pike,"6,729798",7,12,"0,700000","0,800000",3

In [43]:
allExperiments.select { name and globalStats.bestBTree and parameters}.groupBy { parameters.leafNodes }

In [44]:
val df = DataFrame.read("../experiment/optimistic_napier.json")

In [45]:
df.globalStats.bestBTree

bestBTree
└── Selector ├── Sequence │ ...

In [5]:
allExperiments.schema()

name: String
time: Long
generationStats: *
    generation: Int
    population: Int
    bestFitness: Double
    averageFitness: Double
    time: Int
parameters:
    defaultSeed: Int
    populationSize: Int
    maxPhenotypeAge: Int
    mutationProbability: Double
    crossoverProbability: Double
    eliteCount: Int
    tournamentSampleSize: Int
    steadyFitness: Int
    maxGenerations: Int
    maxReparationAttempts: Int
    leafNodes: String
    gridDimensions: Int
    gridObstacles: Int
    maxGridValidationAttempts: Int
    maxNeighbourRadiusForGridValidation: Int
    maxTreeDepth: Int
    minTreeChildren: Int
    maxTreeChildren: Int
    maxSimSteps: Int
    deltaTime: Int
    startVirtualTime: Int
    phototaxisReward: Double
    collisionPenalty: Double
    backtrackingPenalty: Double
    treeComplexityPenalty: Double
    maxTreeSize: Int
    simRunsPerFitnessEval: Int
globalStats:
    leafNodes: List<String>
    mutations: List<String>
    reparations: List<String>
    generations: Int
    altered:
        count: Int
        min: Int
        max: Int
        sum: Int
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    killed:
        count: Int
        min: Int
        max: Int
        sum: Int
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    invalids:
        count: Int
        min: Int
        max: Int
        sum: Int
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    bestBTree: String
    phenotypeAge:
        count: Int
        min: Int
        max: Int
        sum: Int
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    bestFitness:
        count: Int
        min: Double
        max: Double
        sum: Double
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    alterDuration:
        count: Int
        min: Double
        max: Double
        sum: Double
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    evolveDuration:
        count: Int
        min: Double
        max: Double
        sum: Double
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    selectionDuration:
        count: Int
        min: Double
        max: Double
        sum: Double
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double
    evalDuration:
        count: Int
        min: Double
        max: Double
        sum: Double
        mean: Double
        variance: Double
        skewness: Double
        kurtosis: Double